bot:
  token: ${BOT_TOKEN}
  username: ${BOT_NAME}

management:
  endpoint:
    health:
      show-details: "ALWAYS"

spring:
  liquibase:
    change-log: classpath:db/liquibase/db.changelog-master.xml
  jpa:
    open-in-view: false

logging:
  level:
    root: INFO
    it.minetti: DEBUG
